@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Calypso Crypto Asymmetric API 0.2.+ (2024-03-15)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60
!define C_THROW 2C3E50

' -- Styles that don't work with new version of plantuml --
skinparam stereotypeABorderColor #A9DCDF
skinparam stereotypeIBorderColor #B4A7E5
skinparam stereotypeCBorderColor #ADD1B2
skinparam stereotypeEBorderColor #EB937F
' -- END --

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External public API references__ :
    ** <back:yellow>java.security</back>
end legend

package "calypso.crypto.asymmetric" as api {
    package "transaction" as transaction {
        package spi {
            interface AsymmetricCryptoCardTransactionManagerFactorySpi <<red>> {
                +createCardTransactionManager() → AsymmetricCryptoCardTransactionManagerSpi
            }
            interface AsymmetricCryptoCardTransactionManagerSpi <<red>> {
                +initTerminalPkiSession(cardPublicKey: CardPublicKeySpi) → Unit
                {method} <size:10><color:#7F8C8D>    ⚠ errors: AsymmetricCrypto</color></size>
                +updateTerminalPkiSession(cardApdu: ByteArray) → Unit
                {method} <size:10><color:#7F8C8D>    ⚠ errors: AsymmetricCrypto</color></size>
                +isCardPkiSessionValid(cardSessionSignature: ByteArray) → Boolean
                {method} <size:10><color:#7F8C8D>    ⚠ errors: AsymmetricCrypto</color></size>
            }
        }
    }
    exception "AsymmetricCrypto" as AsymmetricCrypto <<green>> <<error>> {
        +val message: String
        +val cause: Any?
    }
    class "AsymmetricCryptoApiProperties" as ApiProperties <<green>> <<constants>> {
        +const VERSION: String = "0.2"
    }
    package "certificate" as certificate {
        package spi {
            together {
            interface PcaCertificateSpi <<red>> {
                +checkCertificateAndGetContent() → CaCertificateContentSpi
                {method} <size:10><color:#7F8C8D>    ⚠ errors: CertificateValidation, AsymmetricCrypto</color></size>
            }
            interface CaCertificateParserSpi <<red>> {
                +getCertificateType() → Byte

                +parseCertificate(cardOutputData: ByteArray) → CaCertificateSpi
                {method} <size:10><color:#7F8C8D>    ⚠ errors: CertificateValidation</color></size>
            }
            interface CaCertificateSpi <<red>> {
                +getIssuerPublicKeyReference() → ByteArray

                +checkCertificateAndGetContent(issuerCertificateContent: CaCertificateContentSpi) → CaCertificateContentSpi
                {method} <size:10><color:#7F8C8D>    ⚠ errors: CertificateValidation, AsymmetricCrypto</color></size>
            }
            interface CardCertificateParserSpi <<red>> {
                +getCertificateType() → Byte

                +parseCertificate(cardOutputData: ByteArray) → CardCertificateSpi
                {method} <size:10><color:#7F8C8D>    ⚠ errors: CertificateValidation</color></size>
            }
            interface CardCertificateSpi <<red>> {
                +getIssuerPublicKeyReference() → ByteArray
                +getCardAid() → ByteArray
                +getCardSerialNumber() → ByteArray

                +checkCertificateAndGetPublicKey(issuerCertificateContent: CaCertificateContentSpi) → CardPublicKeySpi
                {method} <size:10><color:#7F8C8D>    ⚠ errors: CertificateValidation, AsymmetricCrypto</color></size>
            }
            }
            interface CaCertificateContentSpi <<red>> {
                +getPublicKey() → <back:yellow>PublicKey</back>
                +getPublicKeyReference() → ByteArray

                +getStartDate() → Long
                +getEndDate() → Long

                +isAidCheckRequested() → Boolean
                +isAidTruncated() → Boolean
                +getAid() → ByteArray?

                +isCaCertificatesAuthenticationAllowed() → Boolean
                +isCardCertificatesAuthenticationAllowed() → Boolean
            }
            interface CardPublicKeySpi <<red>> {
                +getRawValue() → ByteArray
            }
        }
        exception "CertificateValidation" as CertificateValidation <<green>> <<error>> {
            +val message: String
            +val cause: Any?
        }
    }
}

' Associations

AsymmetricCryptoCardTransactionManagerFactorySpi ..> AsymmetricCryptoCardTransactionManagerSpi #C_LINK : provide >

AsymmetricCryptoCardTransactionManagerSpi ..> CardPublicKeySpi #C_USE : use >

CaCertificateParserSpi .right.> CaCertificateSpi #C_LINK : provide >
CardCertificateParserSpi .right.> CardCertificateSpi #C_LINK : provide >

PcaCertificateSpi ..> CaCertificateContentSpi #C_LINK : provide >

CaCertificateSpi .right.> CaCertificateContentSpi #C_USE : use >
CaCertificateSpi .right.> CaCertificateContentSpi #C_LINK : provide >

CardCertificateSpi .up.> CaCertificateContentSpi #C_USE : use >
CardCertificateSpi .right.> CardPublicKeySpi #C_LINK : provide >

' == LAYOUT ==

PcaCertificateSpi -[hidden]- CaCertificateSpi
CaCertificateParserSpi -[hidden]- CardCertificateParserSpi
CardCertificateSpi -[hidden]- CertificateValidation
AsymmetricCryptoCardTransactionManagerSpi -[hidden]- AsymmetricCrypto
AsymmetricCrypto -[hidden]- ApiProperties

' == STYLE ==

package api #C_GREY1 {}
package api.transaction #C_GREY2 {}
package api.transaction.spi #C_GREY3 {}
package api.certificate #C_GREY2 {}
package api.certificate.spi #C_GREY3 {}

@enduml